default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: abc123xyz@
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: social_buttons_development
test:
  <<: *default
  database: social_buttons_test
production:
  <<: *default
  database: social_buttons_production
  username: social_buttons
  password: <%= ENV['social_buttons_DATABASE_PASSWORD'] %>
